### ISSUE TITLE
Why Does It Need Access To My Browser History?

### ISSUE THREAD

**Issue by t-kitsune** [sergiokas/Extensity#17]

**Comment by sergiokas** [comment]
@t-kitsune it doesn't ask for browser history permissions, see here:

https://github.com/sergiokas/Extensity/blob/master/manifest.json#L17

- Management permission is needed to enable/disable extensions.
- Tabs permission is needed to open apps into new tabs.

That's all.

**Comment by JokerQyou** [comment]
The confirmation dialog does indicate that "it can read your browsing history". See the screenshot below.
![image](https://user-images.githubusercontent.com/1465267/40236411-0e7860c6-5ae0-11e8-8ce4-5f3ba61594f7.png)

**Comment by JokerQyou** [comment]
By reading through some documentation of Chrome extension development, I found [this page](https://developer.chrome.com/extensions/permission_warnings#permissions_with_warnings) that explains `tabs` permission would cause the above warning to be displayed. I've read the source code of Extensity and it's only using `tabs.create` API to open Chrome's builtin extension page. I wonder if there's a better way to do it. But for permission-sensitive users like me, there's currently nothing to worry about. Also I'd suggest adding some explanation about this permission warning to README.

**Comment by sergiokas** [comment]
@JokerQyou yay for open source!

However, I'm investigating a different way to do it since that non-specific message is discouraging a lot of people when installing the extension. I think the requirement for the Tabs API has been removed in recent versions of Chrome if the only thing you want to do is to open a tab; I'll run a few tests and remove the permissions if they aren't really needed anymore.
