### ISSUE TITLE
FR: Left-click popup options for extensions

### ISSUE THREAD

**Issue by ryanwwest** [sergiokas/Extensity#89]
In Chrome, you can left click many extensions to get a smaller popup view of options, on top of the extension's full new tab/new page of complete settings (e.g. uBlock origin has this). I'd like to be able to access an extension's left-click popup menu via Extensity's extension list as well, but I think you can only use many extension's  gear icons that open up the full settings page. The alternative is pinning different extensions so you can always left-click their icons, but only a few icons fit before the URL omnibar gets too small and things feel cluttered.

Is this possible?

**Comment by sergiokas** [comment]
As far as I can tell from the docs, there's no way to launch the popup action of an extension from another extension. Besides (maybe) the security concerns of the approach, I understand the request because since the introduction of "extension pinning" by Google to regain navbar real state on the browser, users have been complaining about their extensions being unpinned without notice.

This is just the way Chrome works, and currently their APIs do not support setting the pinned status or launching the popup of any extension.
